version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3308:3306"
    volumes:
      - ./dataBase:/docker-entrypoint-initdb.d:ro
  server:
    build: ./php
    restart: always
    volumes:
      - ./php:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"
    depends_on:
      - db